import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SharedNavbar } from "@/components/shared/shared-navbar";
import { NuqsAdapter } from "nuqs/adapters/react";
import { Providers } from "@/components/providers";
import { AppPrefetch } from "@/components/app-prefetch";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await new Promise((resolve) => setTimeout(resolve, 1000));
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppPrefetch>
            <SharedNavbar />
            {children}
          </AppPrefetch>
        </Providers>
      </body>
    </html>
  );
}
